=== knime/knime-core/org.knime.core/src/org/knime/core/node/config/XMLConfig_2008_09.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.knime.org/2008/09/XMLConfig"
    targetNamespace="http://www.knime.org/2008/09/XMLConfig"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="config" type="config" />

    <xs:complexType name="config">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="entry" type="entry" />
                <xs:element name="config" type="config" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="entry">
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
        <xs:attribute name="type" type="entry-type" use="required" />
        <xs:attribute name="isnull" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:simpleType name="entry-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="xstring" />
            <xs:enumeration value="xint" />
            <xs:enumeration value="xdouble" />
            <xs:enumeration value="xfloat" />
            <xs:enumeration value="xboolean" />
            <xs:enumeration value="xbyte" />
            <xs:enumeration value="xchar" />
            <xs:enumeration value="xlong" />
            <xs:enumeration value="xshort" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP20810_LineBreaksInWorkflowSetMetaLinkLines/R Source _Table_ (#1)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<entry key="script" type="xstring" value="# https://www.andrewheiss.com/blog/2016/12/08/save-base-graphics-as-pseudo-objects-in-r/%%00010%%00010knime.out &lt;- data.frame(x = 1:100, y=rnorm(100),%%00010                 z=sample(LETTERS[1:3], 100, replace=TRUE))%%00010"/>
<entry key="templateUUID" type="xstring" isnull="true" value=""/>
<entry key="version" type="xstring" value="version 1.x"/>
<entry key="Output non numbers (NaN, Inf, -Inf) as missing cells" type="xboolean" value="false"/>
<entry key="sendRowNames" type="xboolean" value="true"/>
<entry key="sendBatchSize" type="xint" value="10000"/>
<entry key="knimeInType" type="xstring" value="data.frame"/>
</config>
<config key="nodeAnnotation">
<entry key="text" type="xstring" value="create data"/>
<entry key="bgcolor" type="xint" value="16777215"/>
<entry key="x-coordinate" type="xint" value="8"/>
<entry key="y-coordinate" type="xint" value="119"/>
<entry key="width" type="xint" value="104"/>
<entry key="height" type="xint" value="13"/>
<entry key="alignment" type="xstring" value="CENTER"/>
<entry key="borderSize" type="xint" value="0"/>
<entry key="borderColor" type="xint" value="16777215"/>
<entry key="defFontSize" type="xint" value="11"/>
<entry key="annotation-version" type="xint" value="20151123"/>
<config key="styles"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="EXECUTED"/>
<entry key="factory" type="xstring" value="org.knime.r.RReaderTableNodeFactory"/>
<entry key="node-name" type="xstring" value="R Source (Table)"/>
<entry key="node-bundle-name" type="xstring" value="KNIME R-Project nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.r"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-bundle-version" type="xstring" value="3.7.1.v201901291055"/>
<entry key="node-feature-name" type="xstring" value="KNIME Interactive R Statistics Integration"/>
<entry key="node-feature-symbolic-name" type="xstring" value="org.knime.features.r.feature.group"/>
<entry key="node-feature-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-feature-version" type="xstring" value="3.7.1.v201901291055"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="R Source (Table)"/>
<entry key="hasContent" type="xboolean" value="true"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_spec_class" type="xstring" value="org.knime.core.data.DataTableSpec"/>
<entry key="port_object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
<entry key="port_object_summary" type="xstring" value="Rows: 100, Cols: 3"/>
<entry key="port_dir_location" type="xstring" value="port_1"/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/blobsInLoops/Java Edit Variable (#3)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack">
<config key="Variable_0">
<entry key="type" type="xstring" value="variable"/>
<entry key="name" type="xstring" value="tmpFilePath"/>
<entry key="class" type="xstring" value="STRING"/>
<entry key="value" type="xstring" value=""/>
</config>
</config>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<entry key="scriptImports" type="xstring" value="// Your custom imports:%%00010"/>
<entry key="scriptFields" type="xstring" value="// Your custom variables:%%00010"/>
<entry key="scriptBody" type="xstring" value="// set by unit test%%00010String tmpFilePath = System.getProperty(&quot;blobTmpPath&quot;);%%00010if (tmpFilePath == null || tmpFilePath.isEmpty()) {%%00010%%00009throw new Abort(&quot;No system property denoting file path set&quot;);%%00010}%%00010out_tmpFilePath = tmpFilePath;%%00010%%00010%%00010"/>
<config key="jarFiles">
<entry key="array-size" type="xint" value="0"/>
</config>
<config key="outCols">
<entry key="array-size" type="xint" value="0"/>
</config>
<config key="outVars">
<entry key="array-size" type="xint" value="1"/>
<config key="0">
<entry key="Name" type="xstring" value="tmpFilePath"/>
<entry key="JavaName" type="xstring" value="out_tmpFilePath"/>
<entry key="JavaType" type="xstring" value="java.lang.String"/>
<entry key="Type" type="xstring" value="STRING"/>
<entry key="replaceExisting" type="xboolean" value="false"/>
</config>
</config>
<config key="inCols">
<entry key="array-size" type="xint" value="0"/>
</config>
<config key="inVars">
<entry key="array-size" type="xint" value="0"/>
</config>
<entry key="version" type="xstring" value="version 1.x"/>
<entry key="templateUUID" type="xstring" isnull="true" value=""/>
<entry key="runOnExecute" type="xboolean" value="true"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="CONFIGURED"/>
<entry key="factory" type="xstring" value="org.knime.base.node.jsnippet.JavaEditVarNodeFactory"/>
<entry key="node-name" type="xstring" value="Java Edit Variable"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Java Snippet Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.jsnippets"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-bundle-version" type="xstring" value="3.6.0.qualifier"/>
<entry key="node-feature-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
<entry key="node-feature-version" type="xstring" value="0.0.0"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Java Edit Variable"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.tests/src/org/knime/core/node/workflow/testSubnodeView/View (#6)/JavaScript Table View (#3)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<entry key="hideInWizard" type="xboolean" value="false"/>
<entry key="maxRows" type="xint" value="100000"/>
<entry key="enablePaging" type="xboolean" value="true"/>
<entry key="initialPageSize" type="xint" value="10"/>
<entry key="enablePageSizeChange" type="xboolean" value="true"/>
<config key="allowedPageSizes">
<entry key="array-size" type="xint" value="4"/>
<entry key="0" type="xint" value="10"/>
<entry key="1" type="xint" value="25"/>
<entry key="2" type="xint" value="50"/>
<entry key="3" type="xint" value="100"/>
</config>
<entry key="enableShowAll" type="xboolean" value="false"/>
<entry key="enableJumpToPage" type="xboolean" value="false"/>
<entry key="displayRowColors" type="xboolean" value="true"/>
<entry key="displayRowIDs" type="xboolean" value="true"/>
<entry key="displayColumnHeaders" type="xboolean" value="true"/>
<entry key="displayRowIndex" type="xboolean" value="false"/>
<entry key="fixedHeaders" type="xboolean" value="false"/>
<entry key="title" type="xstring" value=""/>
<entry key="subtitle" type="xstring" value=""/>
<config key="columnFilter">
<entry key="filter-type" type="xstring" value="STANDARD"/>
<config key="included_names">
<entry key="array-size" type="xint" value="5"/>
<entry key="0" type="xstring" value="Universe_0_0"/>
<entry key="1" type="xstring" value="Universe_0_1"/>
<entry key="2" type="xstring" value="Universe_1_0"/>
<entry key="3" type="xstring" value="Universe_1_1"/>
<entry key="4" type="xstring" value="Cluster Membership"/>
</config>
<config key="excluded_names">
<entry key="array-size" type="xint" value="0"/>
</config>
<entry key="enforce_option" type="xstring" value="EnforceExclusion"/>
<config key="name_pattern">
<entry key="pattern" type="xstring" value=""/>
<entry key="type" type="xstring" value="Wildcard"/>
<entry key="caseSensitive" type="xboolean" value="true"/>
</config>
<config key="datatype">
<config key="typelist">
<entry key="org.knime.core.data.BooleanValue" type="xboolean" value="false"/>
<entry key="org.knime.core.data.date.DateAndTimeValue" type="xboolean" value="false"/>
<entry key="org.knime.core.data.DoubleValue" type="xboolean" value="false"/>
<entry key="org.knime.core.data.IntValue" type="xboolean" value="false"/>
<entry key="org.knime.core.data.LongValue" type="xboolean" value="false"/>
<entry key="org.knime.core.data.StringValue" type="xboolean" value="false"/>
</config>
</config>
</config>
<entry key="enableSelection" type="xboolean" value="true"/>
<entry key="selectionColumnName" type="xstring" value="Selected (Paged Table View)"/>
<entry key="enableSearching" type="xboolean" value="true"/>
<entry key="enableColumnSearching" type="xboolean" value="false"/>
<entry key="enableSorting" type="xboolean" value="true"/>
<entry key="enableClearSortButton" type="xboolean" value="false"/>
<entry key="globalDateFormat" type="xstring" value="ddd MMM DD YYYY HH:mm:ss"/>
<entry key="enableGlobalNumberFormat" type="xboolean" value="false"/>
<entry key="globalNumberFormatDecimals" type="xint" value="2"/>
<entry key="displayFullscreenButton" type="xboolean" value="true"/>
<entry key="enableHideUnselected" type="xboolean" value="true"/>
<entry key="publishSelection" type="xboolean" value="true"/>
<entry key="subscribeSelection" type="xboolean" value="true"/>
<entry key="publishFilter" type="xboolean" value="true"/>
<entry key="subscribeFilter" type="xboolean" value="true"/>
<entry key="displayMissingValueAsQuestionMark" type="xboolean" value="true"/>
<entry key="globalDateTimeLocale" type="xstring" value="en"/>
<entry key="globalLocalDateFormat" type="xstring" value="YYYY-MM-DD"/>
<entry key="globalLocalDateTimeFormat" type="xstring" value="YYYY-MM-DD"/>
<entry key="globalLocalTimeFormat" type="xstring" value="HH:mm:ss"/>
<entry key="globalZonedDateTimeFormat" type="xstring" value="ddd MMM DD YYYY HH:mm:ss"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="IDLE"/>
<entry key="factory" type="xstring" value="org.knime.js.base.node.viz.pagedTable.PagedTableViewNodeFactory"/>
<entry key="node-name" type="xstring" value="JavaScript Table View"/>
<entry key="node-bundle-name" type="xstring" value="KNIME JavaScript Base Views"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.js.views"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-bundle-version" type="xstring" value="3.4.0.qualifier"/>
<entry key="node-feature-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
<entry key="node-feature-version" type="xstring" value="0.0.0"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="JavaScript Table View"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.testing/src/org/knime/core/node/workflow/bug4352_FileStoreCountInLoopJoin/Row Filter (#10)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="factory" type="xstring" value="org.knime.base.node.preproc.filter.row.RowFilterNodeFactory"/>
<entry key="node-name" type="xstring" value="Row Filter"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME GmbH, Konstanz, Germany"/>
<config key="factory_settings"/>
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<config key="rowFilter">
<entry key="RowFilter_TypeID" type="xstring" value="RowNumber_RowFilter"/>
<entry key="RowRangeStart" type="xint" value="0"/>
<entry key="RowRangeEnd" type="xint" value="0"/>
<entry key="RowRangeInclude" type="xboolean" value="true"/>
</config>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="CONFIGURED"/>
<entry key="name" type="xstring" value="Row Filter"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP20810_LineBreaksInWorkflowSetMetaLinkLines/Image Port Writer (#254)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<config key="file_out_path_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_string"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="file_out_path" type="xstring" value="knime://knime.workflow/../graphic/image.png"/>
<config key="overwrite_ok_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_boolean"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="overwrite_ok" type="xboolean" value="true"/>
</config>
<config key="nodeAnnotation">
<entry key="text" type="xstring" value="image.png"/>
<entry key="bgcolor" type="xint" value="16777215"/>
<entry key="x-coordinate" type="xint" value="1028"/>
<entry key="y-coordinate" type="xint" value="579"/>
<entry key="width" type="xint" value="104"/>
<entry key="height" type="xint" value="13"/>
<entry key="alignment" type="xstring" value="CENTER"/>
<entry key="borderSize" type="xint" value="0"/>
<entry key="borderColor" type="xint" value="16777215"/>
<entry key="defFontSize" type="xint" value="11"/>
<entry key="annotation-version" type="xint" value="20151123"/>
<config key="styles"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="CONFIGURED"/>
<config key="nodecontainer_message">
<entry key="type" type="xstring" value="WARNING"/>
<entry key="message" type="xstring" value="Output file '/Users/m_lauber/Dropbox/knime-workspace/examples/kn_example_r_export_data_rdata/k_001_r_export_data/../graphic/image.png' exists and will be overwritten"/>
</config>
<entry key="factory" type="xstring" value="org.knime.base.node.image.writeimage.WriteImageNodeFactory"/>
<entry key="node-name" type="xstring" value="Image Writer (Port)"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-bundle-version" type="xstring" value="4.1.0.v201912041211"/>
<entry key="node-feature-name" type="xstring" value="KNIME Core"/>
<entry key="node-feature-symbolic-name" type="xstring" value="org.knime.features.base.feature.group"/>
<entry key="node-feature-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-feature-version" type="xstring" value="4.1.0.v201912041824"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Image Writer (Port)"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports"/>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP20810_LineBreaksInWorkflowSetMetaLinkLines/String Manipulation (#6)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<entry key="expression" type="xstring" value="substr($context.workflow.absolute-path$,0 , $var_pos_name$-1)"/>
<entry key="replaced_column" type="xstring" value="var_path_parent_folder"/>
<entry key="append_column" type="xboolean" value="false"/>
<entry key="test_compilation_on_dialog_close" type="xboolean" value="true"/>
<entry key="insert_missing_as_null" type="xboolean" value="false"/>
<entry key="return_type" type="xstring" value="java.lang.String"/>
</config>
<config key="nodeAnnotation">
<entry key="text" type="xstring" value="var_path_parent_folder"/>
<entry key="bgcolor" type="xint" value="16777215"/>
<entry key="x-coordinate" type="xint" value="303"/>
<entry key="y-coordinate" type="xint" value="239"/>
<entry key="width" type="xint" value="114"/>
<entry key="height" type="xint" value="13"/>
<entry key="alignment" type="xstring" value="CENTER"/>
<entry key="borderSize" type="xint" value="0"/>
<entry key="borderColor" type="xint" value="16777215"/>
<entry key="defFontSize" type="xint" value="11"/>
<entry key="annotation-version" type="xint" value="20151123"/>
<config key="styles"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="EXECUTED"/>
<entry key="factory" type="xstring" value="org.knime.base.node.preproc.stringmanipulation.StringManipulationNodeFactory"/>
<entry key="node-name" type="xstring" value="String Manipulation"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Java Snippet Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.jsnippets"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-bundle-version" type="xstring" value="4.1.0.v201911110939"/>
<entry key="node-feature-name" type="xstring" value="KNIME Core"/>
<entry key="node-feature-symbolic-name" type="xstring" value="org.knime.features.base.feature.group"/>
<entry key="node-feature-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-feature-version" type="xstring" value="4.1.0.v201912041824"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="String Manipulation"/>
<entry key="hasContent" type="xboolean" value="true"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_spec_class" type="xstring" value="org.knime.core.data.DataTableSpec"/>
<entry key="port_object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
<entry key="port_object_summary" type="xstring" value="Rows: 1, Cols: 5"/>
<entry key="port_dir_location" type="xstring" value="port_1"/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" value="d4ed14e0-6885-4405-aeee-56dac62fbe13"/>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP2124_ComponentModificationWhileDownstreamExecution/Outer Compon (#11)/Middle Metan (#9)/Inner Compon (#7)/Variable Creator (#6)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack">
        <config key="Variable_0">
            <entry key="type" type="xstring" value="variable"/>
            <entry key="name" type="xstring" value="variable_1"/>
            <entry key="class" type="xstring" value="STRING"/>
            <entry key="value" type="xstring" value=""/>
        </config>
        <config key="Variable_1">
            <entry key="type" type="xstring" value="variable"/>
            <entry key="name" type="xstring" value="variable_1"/>
            <entry key="class" type="xstring" value="STRING"/>
            <entry key="value" type="xstring" value=""/>
        </config>
    </config>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <config key="variableCreationTable_Internals">
            <entry key="SettingsModelID" type="xstring" value="SMITID_variables"/>
            <entry key="EnabledStatus" type="xboolean" value="true"/>
        </config>
        <config key="variables">
            <config key="supportedTypes">
                <entry key="array-size" type="xint" value="5"/>
                <entry key="0" type="xstring" value="str"/>
                <entry key="1" type="xstring" value="int"/>
                <entry key="2" type="xstring" value="long"/>
                <entry key="3" type="xstring" value="double"/>
                <entry key="4" type="xstring" value="bool"/>
            </config>
            <config key="types">
                <entry key="array-size" type="xint" value="1"/>
                <entry key="0" type="xstring" value="str"/>
            </config>
            <config key="names">
                <entry key="array-size" type="xint" value="1"/>
                <entry key="0" type="xstring" value="variable_1"/>
            </config>
            <config key="values">
                <entry key="array-size" type="xint" value="1"/>
                <entry key="0" type="xstring" value=""/>
            </config>
        </config>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="IDLE"/>
    <entry key="factory" type="xstring" value="org.knime.base.node.io.variablecreator.VariableCreatorNodeFactory"/>
    <entry key="node-name" type="xstring" value="Variable Creator"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="5.2.0.v202311171228"/>
    <entry key="node-feature-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-version" type="xstring" value="0.0.0"/>
    <config key="factory_settings"/>
    <entry key="name" type="xstring" value="Variable Creator"/>
    <entry key="hasContent" type="xboolean" value="false"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_dir_location" type="xstring" isnull="true" value=""/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" isnull="true" value=""/>
    </config>
</config>
