=== knime/knime-core/org.knime.core/src/org/knime/core/node/config/XMLConfig_2008_09.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.knime.org/2008/09/XMLConfig"
    targetNamespace="http://www.knime.org/2008/09/XMLConfig"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="config" type="config" />

    <xs:complexType name="config">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="entry" type="entry" />
                <xs:element name="config" type="config" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="entry">
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
        <xs:attribute name="type" type="entry-type" use="required" />
        <xs:attribute name="isnull" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:simpleType name="entry-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="xstring" />
            <xs:enumeration value="xint" />
            <xs:enumeration value="xdouble" />
            <xs:enumeration value="xfloat" />
            <xs:enumeration value="xboolean" />
            <xs:enumeration value="xbyte" />
            <xs:enumeration value="xchar" />
            <xs:enumeration value="xlong" />
            <xs:enumeration value="xshort" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP16962_ReexecutionInNestedComponents/Component (#9)/Nested Compo (#28)/Table View (#26)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack"/>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <entry key="hideInWizard" type="xboolean" value="false"/>
        <config key="columnFilter">
            <entry key="filter-type" type="xstring" value="STANDARD"/>
            <config key="included_names">
                <entry key="array-size" type="xint" value="0"/>
            </config>
            <config key="excluded_names">
                <entry key="array-size" type="xint" value="0"/>
            </config>
            <entry key="enforce_option" type="xstring" value="EnforceExclusion"/>
            <config key="name_pattern">
                <entry key="pattern" type="xstring" value=""/>
                <entry key="type" type="xstring" value="Wildcard"/>
                <entry key="caseSensitive" type="xboolean" value="true"/>
            </config>
            <config key="datatype">
                <config key="typelist"/>
            </config>
        </config>
        <entry key="selectionColumnName" type="xstring" value="Selected (JavaScript Table View)"/>
        <entry key="enablePaging" type="xboolean" value="true"/>
        <entry key="initialPageSize" type="xint" value="10"/>
        <entry key="enablePageSizeChange" type="xboolean" value="true"/>
        <config key="allowedPageSizes">
            <entry key="array-size" type="xint" value="4"/>
            <entry key="0" type="xint" value="10"/>
            <entry key="1" type="xint" value="25"/>
            <entry key="2" type="xint" value="50"/>
            <entry key="3" type="xint" value="100"/>
        </config>
        <entry key="enableShowAll" type="xboolean" value="false"/>
        <entry key="enableJumpToPage" type="xboolean" value="false"/>
        <entry key="displayRowColors" type="xboolean" value="true"/>
        <entry key="displayRowIDs" type="xboolean" value="true"/>
        <entry key="displayColumnHeaders" type="xboolean" value="true"/>
        <entry key="displayRowIndex" type="xboolean" value="false"/>
        <entry key="fixedHeaders" type="xboolean" value="false"/>
        <entry key="title" type="xstring" value=""/>
        <entry key="subtitle" type="xstring" value=""/>
        <entry key="enableSelection" type="xboolean" value="true"/>
        <entry key="enableSearching" type="xboolean" value="true"/>
        <entry key="enableColumnSearching" type="xboolean" value="false"/>
        <entry key="enableSorting" type="xboolean" value="true"/>
        <entry key="enableClearSortButton" type="xboolean" value="false"/>
        <entry key="enableGlobalNumberFormat" type="xboolean" value="false"/>
        <entry key="globalNumberFormatDecimals" type="xint" value="2"/>
        <entry key="displayFullscreenButton" type="xboolean" value="true"/>
        <entry key="enableHideUnselected" type="xboolean" value="true"/>
        <entry key="displayMissingValueAsQuestionMark" type="xboolean" value="true"/>
        <config key="dateTimeFormats_Internals">
            <entry key="SettingsModelID" type="xstring" value="SMID_datetime"/>
            <entry key="EnabledStatus" type="xboolean" value="true"/>
        </config>
        <config key="dateTimeFormats">
            <config key="globalDateTimeLocale_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="globalDateTimeLocale" type="xstring" value="en"/>
            <config key="globalDateFormat_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="globalDateFormat" type="xstring" value="YYYY-MM-DD"/>
            <config key="globalLocalDateFormat_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="globalLocalDateFormat" type="xstring" value="YYYY-MM-DD"/>
            <config key="globalLocalDateTimeFormat_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="globalLocalDateTimeFormat" type="xstring" value="YYYY-MM-DD"/>
            <config key="globalLocalTimeFormat_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="globalLocalTimeFormat" type="xstring" value="HH:mm:ss"/>
            <config key="globalZonedDateTimeFormat_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="globalZonedDateTimeFormat" type="xstring" value="YYYY-MM-DD z"/>
            <config key="timezone_Internals">
                <entry key="SettingsModelID" type="xstring" value="SMID_string"/>
                <entry key="EnabledStatus" type="xboolean" value="true"/>
            </config>
            <entry key="timezone" type="xstring" value="Europe/Berlin"/>
        </config>
        <entry key="singleSelection" type="xboolean" value="false"/>
        <entry key="enableClearSelectionButton" type="xboolean" value="true"/>
        <entry key="maxRows" type="xint" value="100000"/>
        <entry key="enableLazyLoading" type="xboolean" value="false"/>
        <entry key="publishSelection" type="xboolean" value="true"/>
        <entry key="subscribeSelection" type="xboolean" value="true"/>
        <entry key="publishFilter" type="xboolean" value="true"/>
        <entry key="subscribeFilter" type="xboolean" value="true"/>
        <entry key="hideUnselected" type="xboolean" value="false"/>
        <entry key="customCSS" type="xstring" value=""/>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="IDLE"/>
    <entry key="factory" type="xstring" value="org.knime.js.base.node.viz.pagedTable.PagedTableViewNodeFactory"/>
    <entry key="node-name" type="xstring" value="Table View"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME JavaScript Base Views"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.js.views"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="4.4.0.qualifier"/>
    <entry key="node-feature-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-version" type="xstring" value="0.0.0"/>
    <config key="factory_settings"/>
    <entry key="name" type="xstring" value="Table View"/>
    <entry key="hasContent" type="xboolean" value="false"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_dir_location" type="xstring" isnull="true" value=""/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" isnull="true" value=""/>
    </config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP14672_TextOutputInResetExportedWorkflow/Data Generator (#2)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack"/>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <entry key="stddeviation" type="xdouble" value="0.1"/>
        <entry key="noise" type="xdouble" value="0.0"/>
        <entry key="patcount" type="xint" value="100"/>
        <entry key="seed" type="xint" value="1020024507"/>
        <config key="clustercount">
            <entry key="array-size" type="xint" value="2"/>
            <entry key="0" type="xint" value="2"/>
            <entry key="1" type="xint" value="2"/>
        </config>
        <config key="unisize">
            <entry key="array-size" type="xint" value="2"/>
            <entry key="0" type="xint" value="2"/>
            <entry key="1" type="xint" value="2"/>
        </config>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="EXECUTED"/>
    <entry key="factory" type="xstring" value="org.knime.base.node.util.sampledata.SampleDataNodeFactory"/>
    <entry key="node-name" type="xstring" value="Data Generator"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="4.4.0.qualifier"/>
    <entry key="node-feature-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-version" type="xstring" value="0.0.0"/>
    <config key="factory_settings"/>
    <entry key="name" type="xstring" value="Data Generator"/>
    <entry key="hasContent" type="xboolean" value="true"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_spec_class" type="xstring" value="org.knime.core.data.DataTableSpec"/>
            <entry key="port_object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
            <entry key="port_object_summary" type="xstring" value="Rows: 100, Cols: 5"/>
            <entry key="port_dir_location" type="xstring" value="port_1"/>
        </config>
        <config key="port_2">
            <entry key="index" type="xint" value="2"/>
            <entry key="port_spec_class" type="xstring" value="org.knime.core.data.DataTableSpec"/>
            <entry key="port_object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
            <entry key="port_object_summary" type="xstring" value="Rows: 4, Cols: 4"/>
            <entry key="port_dir_location" type="xstring" value="port_2"/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" value="f47342bb-ca88-4482-b322-de0660531eb9"/>
    </config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP19479_Component_Encryption/Component (#4)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack"/>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model"/>
    <config key="nodeAnnotation">
        <entry key="text" type="xstring" value=""/>
        <entry key="bgcolor" type="xint" value="16777215"/>
        <entry key="x-coordinate" type="xint" value="100"/>
        <entry key="y-coordinate" type="xint" value="439"/>
        <entry key="width" type="xint" value="160"/>
        <entry key="height" type="xint" value="21"/>
        <entry key="alignment" type="xstring" value="CENTER"/>
        <entry key="borderSize" type="xint" value="0"/>
        <entry key="borderColor" type="xint" value="0"/>
        <entry key="defFontSize" type="xint" value="-1"/>
        <entry key="annotation-version" type="xint" value="20151123"/>
        <config key="styles"/>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="CONFIGURED"/>
    <entry key="workflow-file" type="xstring" value="workflow.knime"/>
    <entry key="virtual-in-ID" type="xint" value="3"/>
    <config key="inports"/>
    <entry key="virtual-out-ID" type="xint" value="4"/>
    <config key="outports"/>
    <entry key="layoutJSON" type="xstring" value="{&quot;parentLayoutLegacyMode&quot;:false}"/>
    <entry key="configurationLayoutJSON" type="xstring" value="{}"/>
    <entry key="hideInWizard" type="xboolean" value="false"/>
    <entry key="customCSS" type="xstring" value=""/>
</config>

=== knime/knime-core/org.knime.core.testing/src/org/knime/core/node/workflow/bugPE37_subnode_update/Inner Metano (#17)/Table Creator (#1)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<config key="rowIndices">
<entry key="array-size" type="xint" value="2"/>
<entry key="0" type="xint" value="0"/>
<entry key="1" type="xint" value="0"/>
</config>
<config key="columnIndices">
<entry key="array-size" type="xint" value="2"/>
<entry key="0" type="xint" value="0"/>
<entry key="1" type="xint" value="1"/>
</config>
<config key="values">
<entry key="array-size" type="xint" value="2"/>
<entry key="0" type="xstring" value="outdated"/>
<entry key="1" type="xstring" value="hardcoded-old"/>
</config>
<entry key="rowIdPrefix" type="xstring" value="Row"/>
<entry key="rowIdSuffix" type="xstring" value=""/>
<entry key="rowIdStartValue" type="xint" value="0"/>
<entry key="highlightOutputTable" type="xboolean" value="false"/>
<config key="columnProperties">
<config key="0">
<entry key="UserSetValues" type="xboolean" value="true"/>
<entry key="MissValuePattern" type="xstring" value=""/>
<entry key="FormatParameter" type="xstring" isnull="true" value=""/>
<entry key="ReadPossValsFromFile" type="xboolean" value="false"/>
<entry key="SkipThisColumn" type="xboolean" value="false"/>
<entry key="ColumnName" type="xstring" value="metanode-version"/>
<config key="ColumnClass">
<entry key="cell_class" type="xstring" value="org.knime.core.data.def.StringCell"/>
<entry key="is_null" type="xboolean" value="false"/>
</config>
</config>
<config key="1">
<entry key="UserSetValues" type="xboolean" value="true"/>
<entry key="MissValuePattern" type="xstring" value=""/>
<entry key="FormatParameter" type="xstring" isnull="true" value=""/>
<entry key="ReadPossValsFromFile" type="xboolean" value="false"/>
<entry key="SkipThisColumn" type="xboolean" value="false"/>
<entry key="ColumnName" type="xstring" value="value"/>
<config key="ColumnClass">
<entry key="cell_class" type="xstring" value="org.knime.core.data.def.StringCell"/>
<entry key="is_null" type="xboolean" value="false"/>
</config>
</config>
</config>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="CONFIGURED"/>
<entry key="factory" type="xstring" value="org.knime.base.node.io.tablecreator.TableCreator2NodeFactory"/>
<entry key="node-name" type="xstring" value="Table Creator"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME GmbH, Konstanz, Germany"/>
<entry key="node-bundle-version" type="xstring" value="3.2.2.qualifier"/>
<entry key="node-feature-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
<entry key="node-feature-version" type="xstring" value="0.0.0"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Table Creator"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.tests/src/org/knime/core/node/workflow/testCanXYZResponeTimeBug3285/Splitter (#78)/node.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="name" type="xstring" value="Splitter"/>
<config key="model">
<config key="top">
<entry key="array-size" type="xint" value="2"/>
<entry key="0" type="xstring" value="Universe_0_0"/>
<entry key="1" type="xstring" value="Universe_0_1"/>
</config>
<config key="bottom">
<entry key="array-size" type="xint" value="3"/>
<entry key="0" type="xstring" value="Universe_1_0"/>
<entry key="1" type="xstring" value="Universe_1_1"/>
<entry key="2" type="xstring" value="Cluster Membership"/>
</config>
</config>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
<config key="port_2">
<entry key="index" type="xint" value="2"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP21890_UnsetVariablesOnReset/Table Creator (#1)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack"/>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <config key="rowIndices">
            <entry key="array-size" type="xint" value="0"/>
        </config>
        <config key="columnIndices">
            <entry key="array-size" type="xint" value="0"/>
        </config>
        <config key="values">
            <entry key="array-size" type="xint" value="0"/>
        </config>
        <entry key="rowIdPrefix" type="xstring" value="Row"/>
        <entry key="rowIdSuffix" type="xstring" value=""/>
        <entry key="rowIdStartValue" type="xint" value="0"/>
        <entry key="highlightOutputTable" type="xboolean" value="false"/>
        <config key="columnProperties"/>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="CONFIGURED"/>
    <entry key="factory" type="xstring" value="org.knime.base.node.io.tablecreator.TableCreator2NodeFactory"/>
    <entry key="node-name" type="xstring" value="Table Creator"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="5.3.2.v202409100934"/>
    <entry key="node-feature-name" type="xstring" value="MOE Extensions for KNIME"/>
    <entry key="node-feature-symbolic-name" type="xstring" value="com.chemcomp.feature.group"/>
    <entry key="node-feature-vendor" type="xstring" value="Chemical Computing Group ULC."/>
    <entry key="node-feature-version" type="xstring" value="2.5.2.20240913"/>
    <config key="factory_settings"/>
    <entry key="name" type="xstring" value="Table Creator"/>
    <entry key="hasContent" type="xboolean" value="false"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_dir_location" type="xstring" isnull="true" value=""/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" isnull="true" value=""/>
    </config>
</config>

=== knime/knime-core/org.knime.core.tests/src/org/knime/core/node/workflow/bug4409_inactiveInnerLoop/Loop End (#780)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="factory" type="xstring" value="org.knime.base.node.meta.looper.LoopEndNodeFactory"/>
<entry key="node-name" type="xstring" value="Loop End"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME GmbH, Konstanz, Germany"/>
<config key="factory_settings"/>
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="CONFIGURED"/>
<entry key="name" type="xstring" value="Loop End"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="true"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugWEBP803_OnlyResetNodesToBeReexecuted/Component (#9)/String Widget (#8)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack">
        <config key="Variable_0">
            <entry key="type" type="xstring" value="variable"/>
            <entry key="name" type="xstring" value="string-input"/>
            <entry key="class" type="xstring" value="STRING"/>
            <entry key="value" type="xstring" value=""/>
        </config>
    </config>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <config key="defaultValue">
            <entry key="string" type="xstring" value=""/>
        </config>
        <entry key="hideInWizard" type="xboolean" value="false"/>
        <entry key="customCSS" type="xstring" value=""/>
        <entry key="label" type="xstring" value="Label"/>
        <entry key="description" type="xstring" value="Enter Description"/>
        <entry key="required" type="xboolean" value="true"/>
        <entry key="flowVariableName" type="xstring" value="string-input"/>
        <entry key="regex" type="xstring" value=""/>
        <entry key="error_message" type="xstring" value=""/>
        <entry key="editorType" type="xstring" value="Single-line"/>
        <entry key="multilineEditorWidth" type="xint" value="60"/>
        <entry key="multilineEditorHeight" type="xint" value="5"/>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="CONFIGURED"/>
    <entry key="factory" type="xstring" value="org.knime.js.base.node.widget.input.string.StringWidgetNodeFactory"/>
    <entry key="node-name" type="xstring" value="String Widget"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME Quick Form Nodes"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.js.quickforms"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="4.4.0.qualifier"/>
    <entry key="node-feature-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-version" type="xstring" value="0.0.0"/>
    <config key="factory_settings"/>
    <entry key="name" type="xstring" value="String Widget"/>
    <entry key="hasContent" type="xboolean" value="false"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_dir_location" type="xstring" isnull="true" value=""/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" isnull="true" value=""/>
    </config>
</config>
