=== knime/knime-core/org.knime.core/src/org/knime/core/node/config/XMLConfig_2008_09.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.knime.org/2008/09/XMLConfig"
    targetNamespace="http://www.knime.org/2008/09/XMLConfig"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="config" type="config" />

    <xs:complexType name="config">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="entry" type="entry" />
                <xs:element name="config" type="config" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="entry">
        <xs:attribute name="key" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
        <xs:attribute name="type" type="entry-type" use="required" />
        <xs:attribute name="isnull" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:simpleType name="entry-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="xstring" />
            <xs:enumeration value="xint" />
            <xs:enumeration value="xdouble" />
            <xs:enumeration value="xfloat" />
            <xs:enumeration value="xboolean" />
            <xs:enumeration value="xbyte" />
            <xs:enumeration value="xchar" />
            <xs:enumeration value="xlong" />
            <xs:enumeration value="xshort" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/enhAP18918_FunctionalIntegrationTestsForDefBasedCopyPaste/Credentials Configuration (#15)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack">
        <config key="Variable_0">
            <entry key="type" type="xstring" value="variable"/>
            <entry key="name" type="xstring" value="credentials"/>
            <entry key="class" type="xstring" value="CREDENTIALS"/>
            <config key="value">
                <entry key="name" type="xstring" value="credentials"/>
                <entry key="login" type="xstring" value="user"/>
            </config>
        </config>
        <config key="Variable_1">
            <entry key="type" type="xstring" value="variable"/>
            <entry key="name" type="xstring" value="credentials"/>
            <entry key="class" type="xstring" value="CREDENTIALS"/>
            <config key="value">
                <entry key="name" type="xstring" value="credentials"/>
                <entry key="login" type="xstring" value="user"/>
            </config>
        </config>
    </config>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <config key="defaultValue">
            <entry key="username" type="xstring" value="user"/>
            <entry key="isSavePassword" type="xboolean" value="true"/>
            <entry key="passwordEncrypted" type="xpassword" value="02BAAAAGMq_QxveL1vZ0EBj9UiWy7_u1C6"/>
            <entry key="useServerLoginCredentials" type="xboolean" value="false"/>
        </config>
        <entry key="hideInDialog" type="xboolean" value="false"/>
        <entry key="parameterName" type="xstring" value="credentials"/>
        <entry key="label" type="xstring" value="Credential Label"/>
        <entry key="description" type="xstring" value=""/>
        <entry key="required" type="xboolean" value="true"/>
        <entry key="flowVariableName" type="xstring" value="credentials"/>
        <entry key="error_message" type="xstring" value=""/>
        <entry key="prompt_username" type="xboolean" value="true"/>
        <entry key="use_server_login" type="xboolean" value="false"/>
        <entry key="no_display" type="xboolean" value="false"/>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="EXECUTED"/>
    <entry key="factory" type="xstring" value="org.knime.js.base.node.configuration.input.credentials.CredentialsDialogNodeFactory"/>
    <entry key="node-name" type="xstring" value="Credentials Configuration"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME Quick Form Nodes"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.js.quickforms"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="4.6.0.v202202280849"/>
    <entry key="node-feature-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-version" type="xstring" value="0.0.0"/>
    <config key="factory_settings"/>
    <entry key="name" type="xstring" value="Credentials Configuration"/>
    <entry key="hasContent" type="xboolean" value="true"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_spec_class" type="xstring" value="org.knime.core.node.port.flowvariable.FlowVariablePortObjectSpec"/>
            <entry key="port_object_class" type="xstring" value="org.knime.core.node.port.flowvariable.FlowVariablePortObject"/>
            <entry key="port_object_summary" type="xstring" value="Variables connection"/>
            <entry key="port_spec_location" type="xstring" value="spec/spec.zip"/>
            <entry key="port_object_location" type="xstring" value="object/portobject.zip"/>
            <entry key="port_dir_location" type="xstring" value="port_1"/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" value="66017cec-2795-4543-b8d2-be4859f7349b"/>
    </config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP7585_SubnodeInRestoredLoop/Partially Ex (#9)/Row Filter (#7)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<config key="rowFilter">
<entry key="RowFilter_TypeID" type="xstring" value="StringComp_RowFilter"/>
<entry key="ColumnName" type="xstring" value="column1"/>
<entry key="include" type="xboolean" value="true"/>
<entry key="deepFiltering" type="xboolean" value="false"/>
<entry key="CaseSensitive" type="xboolean" value="false"/>
<entry key="Pattern" type="xstring" value="2"/>
<entry key="hasWildCards" type="xboolean" value="false"/>
<entry key="isRegExpr" type="xboolean" value="false"/>
</config>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="EXECUTED"/>
<config key="nodecontainer_message">
<entry key="type" type="xstring" value="WARNING"/>
<entry key="message" type="xstring" value="Node created an empty data table."/>
</config>
<entry key="factory" type="xstring" value="org.knime.base.node.preproc.filter.row.RowFilterNodeFactory"/>
<entry key="node-name" type="xstring" value="Row Filter"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME GmbH, Konstanz, Germany"/>
<entry key="node-bundle-version" type="xstring" value="3.4.0.qualifier"/>
<entry key="node-feature-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
<entry key="node-feature-version" type="xstring" value="0.0.0"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Row Filter"/>
<entry key="hasContent" type="xboolean" value="true"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_spec_class" type="xstring" value="org.knime.core.data.DataTableSpec"/>
<entry key="port_object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
<entry key="port_object_summary" type="xstring" value="Rows: 0, Cols: 1"/>
<entry key="port_dir_location" type="xstring" value="port_1"/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.tests/src/org/knime/core/node/workflow/bug5227_FileStorePortObjectAndLoops/Test FileStore Port Object to Table (#5)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<config key="colName_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_string"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="colName" type="xstring" value="large FS store"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="EXECUTED"/>
<entry key="factory" type="xstring" value="org.knime.testing.node.filestore.fsobject2cell.FileStoreObjectToCellNodeFactory"/>
<entry key="node-name" type="xstring" value="Test FileStore Port Object to Table"/>
<entry key="node-bundle-name" type="xstring" value="Test-Node extension for KNIME Workbench"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.testing"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME GmbH, Konstanz, Germany"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Test FileStore Port Object to Table"/>
<entry key="hasContent" type="xboolean" value="true"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_spec_class" type="xstring" value="org.knime.core.data.DataTableSpec"/>
<entry key="port_object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
<entry key="port_object_summary" type="xstring" value="Rows: 25, Cols: 1"/>
<entry key="port_dir_location" type="xstring" value="port_1"/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" value="372a01a1-183d-4c90-83a0-f36096b1aa94"/>
</config>
</config>

=== knime/knime-core/org.knime.core.testing/src/org/knime/core/node/workflow/bug6029_ExpandSubnode/Sub Node (#8)/Joiner (#4)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<entry key="duplicateHandling" type="xstring" value="AppendSuffixAutomatic"/>
<entry key="compositionMode" type="xstring" value="MatchAll"/>
<entry key="joinMode" type="xstring" value="InnerJoin"/>
<config key="leftTableJoinPredicate">
<entry key="array-size" type="xint" value="1"/>
<entry key="0" type="xstring" value="$RowID$"/>
</config>
<config key="rightTableJoinPredicate">
<entry key="array-size" type="xint" value="1"/>
<entry key="0" type="xstring" value="$RowID$"/>
</config>
<entry key="suffix" type="xstring" value="(*)"/>
<config key="leftIncludeCols">
<entry key="array-size" type="xint" value="1"/>
<entry key="0" type="xstring" value="column_to_be_modified"/>
</config>
<config key="rightIncludeCols">
<entry key="array-size" type="xint" value="1"/>
<entry key="0" type="xstring" value="column_not_to_be_modified"/>
</config>
<entry key="leftIncludeAll" type="xboolean" value="true"/>
<entry key="rightIncludeAll" type="xboolean" value="true"/>
<entry key="rmLeftJoinCols" type="xboolean" value="false"/>
<entry key="rmRightJoinCols" type="xboolean" value="true"/>
<entry key="maxOpenFiles" type="xint" value="200"/>
<entry key="rowKeySeparator" type="xstring" value="_"/>
<entry key="enableHiLite" type="xboolean" value="false"/>
<entry key="numBitsInitial" type="xint" value="6"/>
<entry key="numBitsMaximal" type="xint" value="32"/>
<entry key="usedMemoryThreshold" type="xdouble" value="0.85"/>
<entry key="minAvailableMemory" type="xlong" value="10000000"/>
<entry key="memUseCollectionUsage" type="xboolean" value="true"/>
<entry key="version" type="xstring" value="version_3"/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="IDLE"/>
<entry key="factory" type="xstring" value="org.knime.base.node.preproc.joiner.Joiner2NodeFactory"/>
<entry key="node-name" type="xstring" value="Joiner"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME GmbH, Konstanz, Germany"/>
<entry key="node-bundle-version" type="xstring" value="2.12.0.qualifier"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Joiner"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/bugAP21890_UnsetVariablesOnReset/Component (#22)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack"/>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model"/>
    <config key="nodeAnnotation">
        <entry key="text" type="xstring" value=""/>
        <entry key="contentType" type="xstring" value="text/plain"/>
        <entry key="bgcolor" type="xint" value="16777215"/>
        <entry key="x-coordinate" type="xint" value="0"/>
        <entry key="y-coordinate" type="xint" value="0"/>
        <entry key="width" type="xint" value="0"/>
        <entry key="height" type="xint" value="0"/>
        <entry key="alignment" type="xstring" value="CENTER"/>
        <entry key="borderSize" type="xint" value="0"/>
        <entry key="borderColor" type="xint" value="0"/>
        <entry key="defFontSize" type="xint" value="-1"/>
        <entry key="annotation-version" type="xint" value="20230412"/>
        <config key="styles"/>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="IDLE"/>
    <config key="nodecontainer_message">
        <entry key="type" type="xstring" value="WARNING"/>
        <entry key="message" type="xstring" value="Contains one node with execution failure (Component Input #1)"/>
        <entry key="issue" type="xstring" value="Component Input #1: Component does not have input data, execute upstream nodes first"/>
    </config>
    <entry key="workflow-file" type="xstring" value="workflow.knime"/>
    <entry key="virtual-in-ID" type="xint" value="1"/>
    <config key="inports">
        <config key="inport_0">
            <entry key="index" type="xint" value="0"/>
            <config key="type">
                <entry key="object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
            </config>
        </config>
        <config key="inport_1">
            <entry key="index" type="xint" value="1"/>
            <config key="type">
                <entry key="object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
            </config>
        </config>
    </config>
    <entry key="virtual-out-ID" type="xint" value="2"/>
    <config key="outports"/>
    <entry key="layoutJSON" type="xstring" value="{&quot;parentLayoutLegacyMode&quot;:false}"/>
    <entry key="configurationLayoutJSON" type="xstring" value="{}"/>
    <entry key="hideInWizard" type="xboolean" value="false"/>
    <entry key="customCSS" type="xstring" value=""/>
</config>

=== knime/knime-core/org.knime.core.workflow.tests/src/org/knime/core/node/workflow/testNestedComponentErrorMessages/Component (#22)/Inner Compon (#19)/Duplicate Row Filter (#9)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
<entry key="node_file" type="xstring" value="settings.xml"/>
<config key="flow_stack"/>
<config key="internal_node_subsettings">
<entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
</config>
<config key="model">
<config key="group_cols_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_columnfilter"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<config key="group_cols">
<entry key="filter-type" type="xstring" value="STANDARD"/>
<config key="included_names">
<entry key="array-size" type="xint" value="0"/>
</config>
<config key="excluded_names">
<entry key="array-size" type="xint" value="0"/>
</config>
<entry key="enforce_option" type="xstring" value="EnforceExclusion"/>
<config key="name_pattern">
<entry key="pattern" type="xstring" value=""/>
<entry key="type" type="xstring" value="Wildcard"/>
<entry key="caseSensitive" type="xboolean" value="true"/>
</config>
<config key="datatype">
<config key="typelist"/>
</config>
</config>
<config key="retain_order_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_boolean"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="retain_order" type="xboolean" value="true"/>
<config key="add_row_duplicate_flag_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_boolean"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="add_row_duplicate_flag" type="xboolean" value="true"/>
<config key="add_row_id_flag_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_boolean"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="add_row_id_flag" type="xboolean" value="false"/>
<config key="in_memory_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_boolean"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="in_memory" type="xboolean" value="false"/>
<config key="remove_duplicates_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_boolean"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="remove_duplicates" type="xboolean" value="true"/>
<entry key="row_selection" type="xstring" value="FIRST"/>
<config key="reference_col_Internals">
<entry key="SettingsModelID" type="xstring" value="SMID_string"/>
<entry key="EnabledStatus" type="xboolean" value="true"/>
</config>
<entry key="reference_col" type="xstring" isnull="true" value=""/>
</config>
<entry key="customDescription" type="xstring" isnull="true" value=""/>
<entry key="state" type="xstring" value="IDLE"/>
<config key="nodecontainer_message">
<entry key="type" type="xstring" value="WARNING"/>
<entry key="message" type="xstring" value="At least one column has to be selected for duplicate detection."/>
</config>
<entry key="factory" type="xstring" value="org.knime.base.node.preproc.duplicates.DuplicateRowFilterNodeFactory"/>
<entry key="node-name" type="xstring" value="Duplicate Row Filter"/>
<entry key="node-bundle-name" type="xstring" value="KNIME Base Nodes"/>
<entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.base"/>
<entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
<entry key="node-bundle-version" type="xstring" value="4.2.0.qualifier"/>
<entry key="node-feature-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
<entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
<entry key="node-feature-version" type="xstring" value="0.0.0"/>
<config key="factory_settings"/>
<entry key="name" type="xstring" value="Duplicate Row Filter"/>
<entry key="hasContent" type="xboolean" value="false"/>
<entry key="isInactive" type="xboolean" value="false"/>
<config key="ports">
<config key="port_1">
<entry key="index" type="xint" value="1"/>
<entry key="port_dir_location" type="xstring" isnull="true" value=""/>
</config>
</config>
<config key="filestores">
<entry key="file_store_location" type="xstring" isnull="true" value=""/>
<entry key="file_store_id" type="xstring" isnull="true" value=""/>
</config>
</config>

=== knime/knime-core/org.knime.core.tests/src/test/resources/Component_Template/Call Workflow Service (#2)/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.knime.org/2008/09/XMLConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.knime.org/2008/09/XMLConfig http://www.knime.org/XMLConfig_2008_09.xsd" key="settings.xml">
    <entry key="node_file" type="xstring" value="settings.xml"/>
    <config key="flow_stack"/>
    <config key="internal_node_subsettings">
        <entry key="memory_policy" type="xstring" value="CacheSmallInMemory"/>
    </config>
    <config key="model">
        <entry key="discardJobOnSuccessfulExecution" type="xboolean" value="true"/>
        <entry key="isSynchronous" type="xboolean" value="false"/>
        <entry key="keepFailingJobs" type="xboolean" value="true"/>
        <entry key="workflow" type="xstring" value="/CalleeTest"/>
        <entry key="loadTimeout" type="xint" value="60"/>
        <config key="calleeProperties">
            <config key="inputs">
                <config key="input-0">
                    <entry key="parameterName" type="xstring" value="input-parameter"/>
                    <config key="portType">
                        <entry key="object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
                    </config>
                </config>
            </config>
            <config key="outputs">
                <config key="output-0">
                    <entry key="parameterName" type="xstring" value="output-parameter"/>
                    <config key="portType">
                        <entry key="object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
                    </config>
                </config>
            </config>
        </config>
    </config>
    <entry key="customDescription" type="xstring" isnull="true" value=""/>
    <entry key="state" type="xstring" value="IDLE"/>
    <entry key="factory" type="xstring" value="org.knime.workflowservices.knime.caller.CallWorkflowNodeFactory"/>
    <entry key="node-name" type="xstring" value="Call Workflow Service"/>
    <entry key="node-bundle-name" type="xstring" value="KNIME Nodes to build and use KNIME workflow services"/>
    <entry key="node-bundle-symbolic-name" type="xstring" value="org.knime.workflowservices.labs"/>
    <entry key="node-bundle-vendor" type="xstring" value="KNIME AG, Zurich, Switzerland"/>
    <entry key="node-bundle-version" type="xstring" value="4.6.0.v202112231111"/>
    <entry key="node-feature-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-symbolic-name" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-vendor" type="xstring" isnull="true" value=""/>
    <entry key="node-feature-version" type="xstring" value="0.0.0"/>
    <config key="factory_settings"/>
    <config key="node_creation_config">
        <config key="FileSystem"/>
        <config key="Inputs">
            <config key="port_0">
                <entry key="object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
            </config>
        </config>
        <config key="Outputs">
            <config key="port_0">
                <entry key="object_class" type="xstring" value="org.knime.core.node.BufferedDataTable"/>
            </config>
        </config>
    </config>
    <entry key="name" type="xstring" value="Call Workflow Service"/>
    <entry key="hasContent" type="xboolean" value="false"/>
    <entry key="isInactive" type="xboolean" value="false"/>
    <config key="ports">
        <config key="port_1">
            <entry key="index" type="xint" value="1"/>
            <entry key="port_dir_location" type="xstring" isnull="true" value=""/>
        </config>
    </config>
    <config key="filestores">
        <entry key="file_store_location" type="xstring" isnull="true" value=""/>
        <entry key="file_store_id" type="xstring" isnull="true" value=""/>
    </config>
</config>
